apiVersion: v1
kind: Service
metadata:
  name: nginx-service3
spec:
  type: NodePort
  selector:
    app: nginx-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
